### ISSUE TITLE
Range input

### ISSUE THREAD

**Issue by wille** [bitrefill/airfill-widget#137]
Not satisfied with this and can easily be made better I think.

![image](https://user-images.githubusercontent.com/18327818/44342759-4a13fa00-a48c-11e8-94bb-bc8723886136.png)

**Comment by ziggamon** [comment]
Let's move this towards the mockups that Anna made some months back

**Comment by wille** [comment]
I'm going to start work on this.

![image](https://user-images.githubusercontent.com/18327818/44400704-768f4b00-a54c-11e8-80b1-bb448edfeccc.png)

We really need to add exchange rates for all different cryptos we accept.

**Comment by wille** [comment]
deployment should be up here soon https://github.com/bitrefill/airfill-widget/pull/138

**Comment by ziggamon** [comment]
<img width="712" alt="screen shot 2018-08-21 at 17 07 29" src="https://user-images.githubusercontent.com/92292/44410462-b7935980-a564-11e8-952a-ad471f2e963c.png">

**Comment by wille** [comment]
@ziggamon What should separate the packages and the custom amounts views, or should we combine them as it is today

**Comment by ziggamon** [comment]
No need to show packages if there's a range

**Comment by wille** [comment]
What do we want prefilled in ranged input?

**Comment by ziggamon** [comment]
In this order:

1) Whatever amount the user bought last time
2) Maximum amount his balance can afford
3) Average order size per the statistics call

**Comment by wille** [comment]
@ziggamon 

1. Do we store this, or should we cache this nicely on the client side
2. We should have an upper limit here? Might be edge cases where users accidentally buy with all balance they have.

**Comment by ziggamon** [comment]
1. Cache client side is fine. Also has benefit of working for non-account users.

2. Nah, the whole point is that they should? there are two more steps of confirmation after. Many users currently try to guesstimate what the maximum is that they afford, this way we help them with that. 

In practice it will in most cases end up in 1 because who would deposit first a bunch of money that has never made a purchase at all? Also, might be useful to add a mode 1.2: If the number in 1 is higher than the number in 2 (max limit) then use 2 (show the max that they afford).

**Comment by wille** [comment]
any thoughts on this? single pkg products
![image](https://user-images.githubusercontent.com/18327818/44656619-d9c02800-a9f9-11e8-9080-985f554bbb42.png)

**Comment by ziggamon** [comment]
Are there any others than reddit? Or what's the issue specifically, you want to bypass this step?

**Comment by wille** [comment]
@ziggamon was thinking if it's fine how it looks with only 1 package available

**Comment by ziggamon** [comment]
Yeah, it's a strict improvement from before!

**Comment by wille** [comment]
Merged.
